--1)
SELECT BRAND_CD, COUNT(INVOICE_NO) 
  FROM A_OUT_M
 GROUP BY BRAND_CD;

--2)
SELECT SUM(ORDER_QTY)
  FROM A_OUT_D
 WHERE BRAND_CD = '1001' 
   AND ITEM_CD = 'A';

--3)
SELECT D.BRAND_CD, D.ITEM_CD, SUM(D.ORDER_QTY)
  FROM A_OUT_D D
  JOIN A_OUT_M M 
    ON D.BRAND_CD = M.BRAND_CD
   AND D.INVOICE_NO = M.INVOICE_NO
 WHERE M.OUTBOUND_DATE = TO_DATE('2023-01-03', 'YYYY-MM-DD')
 GROUP BY D.BRAND_CD, D.ITEM_CD;

SELECT D.BRAND_CD, D.ITEM_CD, SUM(D.ORDER_QTY)
  FROM A_OUT_D
 WHERE (BRAND_CD, INVOICE_NO) IN (
                                  SELECT BRAND_CD, INVOICE_NO
                                    FROM A_OUT_M
                                   WHERE OUTBOUND_DATE = '2023-01-03'
                                 )
 GROUP BY BRAND_CD, ITEM_CD
 ORDER BY BRAND_CD, ITEM_CD;


--1) 
SELECT *
  FROM A_OUT_M
 WHERE OUTBOUND_DATE = TO_DATE('2023-01-03');

--2)
SELECT *
  FROM A_OUT_M
 WHERE OUTBOUND_DATE = TO_DATE('2023-01-04')
   AND ORDER_NM = '김민기';
   
--3)
SELECT *
  FROM A_OUT_D
 WHERE ITEM_CD = 'A';
 
--4)
SELECT *
  FROM A_OUT_D D
 WHERE ITEM_CD = 'C'
   AND ORDER_QTY >= 3;
   
--5)
--SELECT *
--  FROM A_ITEM
--  


--1)
SELECT BRAND_CD, INVOICE_NO, ORDER_NM
  FROM A_OUT_M
 WHERE OUTBOUND_DATE IN ('2023-01-03', '2023-01-04');
 
--2)
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
  FROM A_OUT_D
 WHERE BRAND_CD = '1001'
   AND ITEM_CD IN ('A', 'B', 'C')            
   AND ORDER_QTY >= 3;
   
   
--1)
SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE, ORDER_NM
  FROM A_OUT_M
 WHERE OUTBOUND_DATE BETWEEN '2023-01-01' AND '2023-01-04'
   AND ORDER_NM IN ('윤현수', '김민기');
   
--2)
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
  FROM A_OUT_D
 WHERE INVOICE_NO BETWEEN '#01' AND '#05'
   AND ITEM_CD IN ('A', 'B', 'C')
   AND ORDER_QTY >= 3;
   

--1)
SELECT BRAND_CD, INVOICE_NO, OUTBOUND_DATE, ORDER_NM
  FROM A_OUT_M
 WHERE INVOICE_NO BETWEEN '#01' AND '#05'
   AND (ORDER_NM LIKE '전%' OR ORDER_NM LIKE '권%');
--   AND REGEXP_LIKE(ORDER_NM, '^(전|권)');   
--   AND SUBSTR(ORDER_NM, 1, 1) IN ('권', '전');
   
--2)
SELECT BRAND_CD, INVOICE_NO, ITEM_CD, ORDER_QTY
  FROM A_OUT_D
 WHERE INVOICE_NO LIKE '#0%'
   AND ORDER_QTY >= 3;