--1) 1월 4일에 B상품 또는 D상품을 주문한 주문의 [브랜드], [출고일자], [인보이스], [라인번호], [주문수량]을 표시
SELECT M.BRAND_CD, M.OUTBOUND_DATE, M.INVOICE_NO, D.LINE_NO, D.ORDER_QTY
  FROM A_OUT_M M
  JOIN A_OUT_D D ON M.BRAND_CD   = D.BRAND_CD
                AND M.INVOICE_NO = D.INVOICE_NO
 WHERE OUTBOUND_DATE = TO_DATE('2023-01-04')
;

--2) 1월 3일에서 1월 4일 사이에 B상품 또는 D상품을 주문한 주문의 [브랜드], [출고일자], [상품코드], [주문수량 합계]를 표시
SELECT M.BRAND_CD, M.OUTBOUND_DATE, D.ITEM_CD, SUM(D.ORDER_QTY)
  FROM A_OUT_M M
  JOIN A_OUT_D D ON M.BRAND_CD   = D.BRAND_CD
                AND M.INVOICE_NO = D.INVOICE_NO
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-03') 
                         AND TO_DATE('2023-01-04')
   AND D.ITEM_CD IN ('B', 'D')
 GROUP BY M.BRAND_CD, M.OUTBOUND_DATE, D.ITEM_CD
 ORDER BY M.BRAND_CD
;

--3) 1001 브랜드에서 1월 4일부터 1월 5일 사이에 주문한 인보이스들 중에서 총 주문수량이 가장 많은 [인보이스], [주문자]를 표시
SELECT * 
  FROM (
        SELECT M.INVOICE_NO, M.ORDER_NM
          FROM A_OUT_M M
          JOIN A_OUT_D D ON M.BRAND_CD   = D.BRAND_CD
                        AND M.INVOICE_NO = D.INVOICE_NO
         WHERE M.BRAND_CD = '1001'
           AND M.OUTBOUND_DATE BETWEEN TO_DATE('2023-01-04')
                                   AND TO_DATE('2023-01-05')
         GROUP BY M.INVOICE_NO, M.ORDER_NM
         ORDER BY SUM(D.ORDER_QTY) DESC
       )
 WHERE ROWNUM = 1 
-- FETCH FIRST 1 ROWS ONLY
;

--4) 1월 1일부터 1월 4일 사이에 3개 이상 주문한 상품이 있는 주문의 [브랜드], [출고일자], [인보이스], [상품코드], [상품명], [주문수량]을 표시
SELECT M.BRAND_CD
      ,M.OUTBOUND_DATE
      ,M.INVOICE_NO
      ,D.ITEM_CD 
      ,I.ITEM_NM
      ,SUM(D.ORDER_QTY) AS SUM_QTY
  FROM A_OUT_M M
  JOIN A_OUT_D D ON M.BRAND_CD   = D.BRAND_CD
                AND M.INVOICE_NO = D.INVOICE_NO
  JOIN A_ITEM I ON D.BRAND_CD = I.BRAND_CD
               AND D.ITEM_CD  = I.ITEM_CD
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-01') 
                         AND TO_DATE('2023-01-04')
 GROUP BY M.BRAND_CD, M.OUTBOUND_DATE, M.INVOICE_NO, D.ITEM_CD, I.ITEM_NM
HAVING SUM(D.ORDER_QTY) >= 3
 ORDER BY M.BRAND_CD, M.OUTBOUND_DATE, M.INVOICE_NO
;

--5) 1월 1일부터 1월 4일 사이에 [브랜드별] & [상품별] 주문수량 합계를 표시하되, 상품명과 입수는 조인을 이용해 표시
SELECT M.BRAND_CD, M.OUTBOUND_DATE, D.ITEM_CD, I.ITEM_NM, I.QTY_IN_BOX, SUM(D.ORDER_QTY)
  FROM A_OUT_M M
  JOIN A_OUT_D D ON M.BRAND_CD   = D.BRAND_CD
                AND M.INVOICE_NO = D.INVOICE_NO
  JOIN A_ITEM I ON D.BRAND_CD = I.BRAND_CD
               AND D.ITEM_CD  = I.ITEM_CD
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-01') 
                         AND TO_DATE('2023-01-04')
 GROUP BY M.BRAND_CD, M.OUTBOUND_DATE, D.ITEM_CD, I.ITEM_NM, I.QTY_IN_BOX
 ORDER BY M.BRAND_CD, M.OUTBOUND_DATE
;

--6) 위 결과에 인라인뷰를 적용하여 박스수, 낱개수량을 표시
SELECT BRAND_CD, OUTBOUND_DATE, ITEM_CD, ITEM_NM, QTY_IN_BOX, SUM_QTY
      ,TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_QTY
      ,MOD(SUM_QTY, QTY_IN_BOX) AS PCS_QTY
  FROM (
        SELECT M.BRAND_CD, M.OUTBOUND_DATE, D.ITEM_CD, I.ITEM_NM, I.QTY_IN_BOX, SUM(D.ORDER_QTY) AS SUM_QTY
          FROM A_OUT_M M
          JOIN A_OUT_D D ON M.BRAND_CD   = D.BRAND_CD
                        AND M.INVOICE_NO = D.INVOICE_NO
          JOIN A_ITEM I ON D.BRAND_CD = I.BRAND_CD
                       AND D.ITEM_CD  = I.ITEM_CD
         WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-01') 
                                 AND TO_DATE('2023-01-04')
         GROUP BY M.BRAND_CD, M.OUTBOUND_DATE, D.ITEM_CD, I.ITEM_NM, I.QTY_IN_BOX
         ORDER BY M.BRAND_CD, M.OUTBOUND_DATE
       )
;

--7) 위 결과에 인라인뷰를 적용하여 박스수가 가장 많은 TOP3만 표시
SELECT * 
  FROM (
        SELECT BRAND_CD, OUTBOUND_DATE, ITEM_CD, ITEM_NM, QTY_IN_BOX, SUM_QTY
              ,TRUNC(SUM_QTY / QTY_IN_BOX) AS BOX_QTY
              ,MOD(SUM_QTY, QTY_IN_BOX) AS PCS_QTY
          FROM (
                SELECT M.BRAND_CD, M.OUTBOUND_DATE, D.ITEM_CD, I.ITEM_NM, I.QTY_IN_BOX, SUM(D.ORDER_QTY) AS SUM_QTY
                  FROM A_OUT_M M
                  JOIN A_OUT_D D ON M.BRAND_CD   = D.BRAND_CD
                                AND M.INVOICE_NO = D.INVOICE_NO
                  JOIN A_ITEM I ON D.BRAND_CD = I.BRAND_CD
                               AND D.ITEM_CD  = I.ITEM_CD
                 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2023-01-01') 
                                         AND TO_DATE('2023-01-04')
                 GROUP BY M.BRAND_CD, M.OUTBOUND_DATE, D.ITEM_CD, I.ITEM_NM, I.QTY_IN_BOX
                 ORDER BY M.BRAND_CD, M.OUTBOUND_DATE
               )
         ORDER BY BOX_QTY DESC
        )
 WHERE ROWNUM <= 3
;

-- CS_NO 테이블의 활용 방법1 (날짜 연산)
SELECT LEVEL
  FROM DUAL
 CONNECT BY LEVEL <= 10
;

SELECT TRUNC(SYSDATE) + LEVEL
  FROM DUAL
 CONNECT BY LEVEL <= 10
;

SELECT COUNT(1)
  FROM DUAL
 CONNECT BY LEVEL <= TO_DATE('2026-12-31', 'YYYY-MM-DD') - TRUNC(SYSDATE)
;

-- CS_NO 테이블의 활용 방법2 (레코드 복제)
-- 고정배수 복제
SELECT *
  FROM (
        SELECT 'A' AS ITEM, 1 AS QTY FROM DUAL UNION ALL
        SELECT 'A' AS ITEM, 2 AS QTY FROM DUAL
       ) M1
       JOIN CS_NO C1 ON C1.NO <= 20;
       
-- 변동배수 복제
SELECT *
  FROM (
        SELECT 'A' AS ITEM, 1 AS QTY FROM DUAL UNION ALL
        SELECT 'A' AS ITEM, 2 AS QTY FROM DUAL UNION ALL
        SELECT 'A' AS ITEM, 2 AS QTY FROM DUAL 
       ) M1
       JOIN CS_NO C1 ON C1.NO <= M1.QTY;

-- 실전문제 1) 3개 테이블 조인
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_CD, C1.ITEM_NM, M2.ORDER_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M1.INVOICE_NO = M2.INVOICE_NO
       JOIN CM_ITEM C1 ON M2.ITEM_CD = C1.ITEM_CD
 WHERE M1.INVOICE_NO IN ('346724703834', '346724722535', '346724717915')
 ORDER BY M1.INVOICE_NO, M2.LINE_NO
;

-- 실전문제 2) 한 SQL에서 동일한 테이블을 2회 이상 조인에 참여시키는 형태 연습하기
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_CD, C1.ITEM_NM, M2.ORDER_QTY
      ,C2.CODE_NM AS TEMP_NM
      ,C3.CODE_NM AS OUT_TYPE_NM
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
       JOIN CM_ITEM  C1 ON C1.ITEM_CD = M2.ITEM_CD
       JOIN CS_CODE  C2 ON C2.CODE_GRP   = 'LDIV01'
                       AND C2.CODE_CD    = M1.TEMP_DIV 
       JOIN CS_CODE  C3 ON C3.CODE_GRP   = 'LDIV03'
                       AND C3.CODE_CD    = M1.OUT_TYPE_DIV
 WHERE M1.INVOICE_NO IN ('346724703834', '346724722535', '346724717915')
 ORDER BY M1.INVOICE_NO, M2.LINE_NO
