-- 데이터 압축하기 1
--1)
SELECT OUTBOUND_DATE, SUM(ORDER_QTY) AS SUM_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUT_DATE || '01', 'YYYY-MM-DD') AND LAST_DAY(TO_DATE(:OUT_DATE || '01', 'YYYY-MM-DD'))
 GROUP BY M1.OUTBOUND_DATE
 ORDER BY SUM_QTY DESC
;

--2)
SELECT SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'D'), '1', M2.ORDER_QTY, 0)) AS SUN
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'D'), '2', M2.ORDER_QTY, 0)) AS MON
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'D'), '3', M2.ORDER_QTY, 0)) AS TUE
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'D'), '4', M2.ORDER_QTY, 0)) AS WED
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'D'), '5', M2.ORDER_QTY, 0)) AS THU
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'D'), '6', M2.ORDER_QTY, 0)) AS FRI
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'D'), '7', M2.ORDER_QTY, 0)) AS SAT
  FROM LO_OUT_M M1 
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUT_DATE || '01', 'YYYYMMDD') 
                            AND LAST_DAY(TO_DATE(:OUT_DATE || '01', 'YYYYMMDD'))
;

SELECT TO_CHAR(M1.OUTBOUND_DATE, 'DAY') AS DAY
      ,SUM(ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_M M1 
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUT_DATE || '01', 'YYYYMMDD') AND LAST_DAY(TO_DATE(:OUT_DATE || '01', 'YYYYMMDD'))
 GROUP BY TO_CHAR(M1.OUTBOUND_DATE, 'DAY')
         ,TO_CHAR(M1.OUTBOUND_DATE, 'D') -- D로 정렬해야 하는 이유:
 ORDER BY TO_CHAR(M1.OUTBOUND_DATE, 'D') -- ORDER BY에는 GROUP BY, WHERE, 집계함수 제외한 SELECT 컬럼에 존재하는 컬럼만 올 수 있음
;

--3)
SELECT SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '01', M2.ORDER_QTY)) AS M01
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '02', M2.ORDER_QTY)) AS M02
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '03', M2.ORDER_QTY)) AS M03
      ,SUM(CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'MM') IN ('01', '02', '03') THEN M2.ORDER_QTY END) AS Q1
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '04', M2.ORDER_QTY)) AS M04
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '05', M2.ORDER_QTY)) AS M05
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '06', M2.ORDER_QTY)) AS M06
      ,SUM(CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'MM') IN ('04', '05', '06') THEN M2.ORDER_QTY END) AS Q2
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '07', M2.ORDER_QTY)) AS M07
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '08', M2.ORDER_QTY)) AS M08
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '09', M2.ORDER_QTY)) AS M09
      ,SUM(CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'MM') IN ('07', '08', '09') THEN M2.ORDER_QTY END) AS Q3
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '10', M2.ORDER_QTY)) AS M10
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '11', M2.ORDER_QTY)) AS M11
      ,SUM(DECODE(TO_CHAR(M1.OUTBOUND_DATE, 'MM'), '12', M2.ORDER_QTY)) AS M12
      ,SUM(CASE WHEN TO_CHAR(M1.OUTBOUND_DATE, 'MM') IN ('10', '11', '12') THEN M2.ORDER_QTY END) AS Q4
  FROM LO_OUT_M M1 
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_DATE(:OUT_DATE || '0101', 'YYYYMMDD') 
                            AND TO_DATE(:OUT_DATE || '1231', 'YYYYMMDD')
;

--4)
SELECT CASE WHEN RNUM <= 5 THEN TO_CHAR(RNUM) ELSE '0' END AS RNUM
      ,CASE WHEN RNUM <= 5 THEN ITEM_CD ELSE '99999' END AS ITEM_CD
      ,CASE WHEN RNUM <= 5 THEN ITEM_NM ELSE 'TOP5제외 합계' END AS ITEM_NM
      ,SUM(ORDER_QTY) AS ORDER_QTY
  FROM (
        SELECT ROW_NUMBER() OVER(ORDER BY SUM(ORDER_QTY) DESC) AS RNUM
              ,ITEM_CD
              ,ITEM_NM
              ,SUM(ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE OUTBOUND_DATE BETWEEN '2019-06-01' AND '2019-06-30'
           AND ITEM_NM LIKE '%참치%'
         GROUP BY ITEM_CD, ITEM_NM
       )
 GROUP BY CASE WHEN RNUM <= 5 THEN TO_CHAR(RNUM) ELSE '0' END 
         ,CASE WHEN RNUM <= 5 THEN ITEM_CD ELSE '99999' END
         ,CASE WHEN RNUM <= 5 THEN ITEM_NM ELSE 'TOP5제외 합계' END
 ORDER BY CASE WHEN ITEM_CD = '99999' THEN 2 ELSE 1 END
         ,ORDER_QTY DESC
;


-- 데이터 압축하기 2
--1) 컬럼 연계 최대값 구하기
SELECT  AS DAYY
      ,OUTBOUND_DATE
      ,SUM(ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('201909' || '01', 'YYYYMMDD') 
                            AND LAST_DAY(TO_DATE('201909', 'YYYYMM')) 
 GROUP BY OUTBOUND_DATE