-- 조인활용 1
--1)
SELECT *
  FROM (
        SELECT M1.INVOICE_NO, M1.OUTBOUND_NO, M1.OUTBOUND_BATCH, M2.ITEM_CD, M2.ITEM_NM, M2.ORDER_QTY
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M1.INVOICE_NO = M2.INVOICE_NO
          WHERE OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
            AND M2.ITEM_NM LIKE '%골뱅이%'
          ORDER BY M2.ORDER_QTY DESC
       )
 WHERE ROWNUM <= 5
;

--2)
SELECT M2.ITEM_CD, C1.ITEM_NM, SUM(M2.ORDER_QTY) AS ORDER_QTY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M1.INVOICE_NO = M2.INVOICE_NO
       JOIN CM_ITEM C1 ON C1.ITEM_CD = M2.ITEM_CD
 WHERE OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
   AND OUT_BOX_DIV = 'D5'
 GROUP BY M2.ITEM_CD, C1.ITEM_NM
 ORDER BY ORDER_QTY DESC
;

--3)
SELECT M1.INVOICE_NO, M1.OUTBOUND_DATE, M1.OUT_TYPE_DIV, M2.LINE_NO, M2.ITEM_CD, M2.ITEM_NM, M2.ORDER_QTY
      ,NVL(C2.CODE_NM, 'Failed..') AS TEMP_NM
      ,C3.CODE_NM AS OUT_TYPE_NM
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M1.INVOICE_NO = M2.INVOICE_NO
       JOIN CM_ITEM C1  ON C1.ITEM_CD    = M2.ITEM_CD
  LEFT JOIN CS_CODE C2  ON C2.CODE_GRP   = 'LDIV011'
                       AND C2.CODE_CD    = M1.TEMP_DIV
       JOIN CS_CODE C3  ON C3.CODE_GRP   = 'LDIV03'
                       AND C3.CODE_CD       = M1.OUT_TYPE_DIV 
 WHERE M1.INVOICE_NO IN ('346724703834', '346724722535', '346724717915')
 ORDER BY M1.INVOICE_NO, M2.LINE_NO
;

--4)
SELECT OUT_DATE, NVL(QTY, 0) AS QTY
  FROM (
        SELECT TRUNC(TO_DATE(:OUTBOUND_DATE), 'MM') + NO-1 AS OUT_DATE
          FROM CS_NO  
         WHERE NO <= TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD') - TRUNC(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') + 1
       ) T1
  LEFT JOIN (
             SELECT OUTBOUND_DATE, SUM(ORDER_QTY) AS QTY
               FROM LO_OUT_M M1
                    JOIN LO_OUT_D M2 ON M1.INVOICE_NO = M2.INVOICE_NO
              WHERE OUTBOUND_DATE BETWEEN TRUNC(TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD'), 'MM') AND TO_DATE(:OUTBOUND_DATE, 'YYYY-MM-DD')
              GROUP BY OUTBOUND_DATE
              ORDER BY OUTBOUND_DATE
            ) T2 ON T1.OUT_DATE = T2.OUTBOUND_DATE
 ORDER BY OUT_DATE
;

-- 조인활용 2
--1) 파티션 있는 누적수량 구하기 (분석함수 배제)
SELECT M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
      ,SUM(M2.ORDER_QTY) AS ACC_ORDER_QTY
  FROM LO_OUT_D M1 -- 기준 테이블 M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO 
                       AND M2.LINE_NO   <= M1.LINE_NO
 WHERE M1.INVOICE_NO IN ('346724703845', '346724706214')
 GROUP BY M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
 ORDER BY M1.INVOICE_NO, M1.LINE_NO
;

--2) 파티션 없는 누적수량 구하기 (분석함수 배제)
SELECT M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
      ,SUM(M2.ORDER_QTY) AS ACC_ORDER_QTY
  FROM LO_OUT_D M1
       JOIN LO_OUT_D M2 ON (M2.INVOICE_NO < M1.INVOICE_NO) 
                        OR (M2.INVOICE_NO = M1.INVOICE_NO AND M2.LINE_NO <= M1.LINE_NO)
 WHERE M1.INVOICE_NO IN ('346724703845', '346724706214')
   AND M2.INVOICE_NO IN ('346724703845', '346724706214')
 GROUP BY M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
 ORDER BY M1.INVOICE_NO, M1.LINE_NO
;

-- 교수님 풀이 1
SELECT M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
      ,SUM(M2.ORDER_QTY) AS ACC_ORDER_QTY
  FROM LO_OUT_D M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO IN ('346724703845', '346724706214')
                       AND M2.INVOICE_NO || LPAD(M2.LINE_NO, 3, '0') <= M1.INVOICE_NO || LPAD(M1.LINE_NO, 3, '0') 
  WHERE M1.INVOICE_NO IN ('346724703845', '346724706214')
  GROUP BY M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ITEM_NM, M1.ORDER_QTY
  ORDER BY M1.INVOICE_NO, M1.LINE_NO
;

-- 교수님 풀이 2
WITH MY_SET
AS (
    SELECT INVOICE_NO, LINE_NO, ITEM_CD, ORDER_QTY
          ,ROW_NUMBER() OVER(ORDER BY INVOICE_NO, LINE_NO) AS RNUM
      FROM LO_OUT_D
     WHERE INVOICE_NO IN ('346724703845', '346724706214')
   )
SELECT M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ORDER_QTY, SUM(M2.ORDER_QTY) AS SUM_QTY
  FROM MY_SET M1
       JOIN MY_SET M2 ON M2.RNUM <= M1.RNUM
 GROUP BY M1.INVOICE_NO, M1.LINE_NO, M1.ITEM_CD, M1.ORDER_QTY
 ORDER BY M1.INVOICE_NO, M1.LINE_NO
;

--1) 하나의 SQL로 상황에 따라 정렬하기(숫자)
SELECT OUTBOUND_DATE, INVOICE_NO, WORK_SEQ
  FROM LO_OUT_M
 WHERE OUTBOUND_DATE BETWEEN TO_DATE('2019-06-03', 'YYYY-MM-DD') AND TO_DATE('2019-06-04', 'YYYY-MM-DD')
   AND SET_TYPE_CD = '000581225'
   AND SET_QTY = 3
 ORDER BY 
       CASE WHEN :SORT_TYPE = 1 THEN WORK_SEQ END
      ,CASE WHEN :SORT_TYPE = 2 THEN WORK_SEQ END DESC,
--       WORK_SEQ * CASE :SORT_TYPE WHEN '1' THEN 1 ELSE -1 END   
       INVOICE_NO
;

-- 2) 하나의 SQL로 상황에 따라 정렬하기(문자열)
SELECT INVOICE_NO, LINE_NO, ITEM_NM
  FROM LO_OUT_D
 WHERE INVOICE_NO = '346724704405'
 ORDER BY
       CASE WHEN :SORT_TYPE = 1 THEN ITEM_NM END
      ,CASE WHEN :SORT_TYPE = 2 THEN ITEM_NM END DESC
;


-- 분석함수 1
SELECT INVOICE_NO, LINE_NO, ITEM_NM, ORDER_QTY
  FROM LO_OUT_D
 WHERE INVOICE_NO IN ('346724705050', '346724705061')
 ORDER BY INVOICE_NO, LINE_NO
;

SELECT INVOICE_NO, LINE_NO, ITEM_NM, ORDER_QTY
      ,SUM(ORDER_QTY) OVER() AS TOT_SUM
      ,SUM(ORDER_QTY) OVER(PARTITION BY INVOICE_NO) AS PART_SUM
      ,SUM(ORDER_QTY) OVER(PARTITION BY INVOICE_NO ORDER BY LINE_NO) AS ACC_PART_SUM
      ,SUM(ORDER_QTY) OVER(ORDER BY INVOICE_NO, LINE_NO) AS ACC_SUM
      ,COUNT(*) OVER() AS TOT_CNT
      ,COUNT(*) OVER(PARTITION BY INVOICE_NO) AS PART_CNT
      ,COUNT(DISTINCT INVOICE_NO) OVER() AS UNQ_CNT
      ,LAG(ITEM_NM) OVER(ORDER BY INVOICE_NO, LINE_NO) AS TOT_LAG
      ,LEAD(ITEM_NM) OVER(ORDER BY INVOICE_NO, LINE_NO) AS TOT_LEAD
  FROM LO_OUT_D
 WHERE INVOICE_NO IN ('346724705050', '346724705061')
;

-- 1) 분석함수 MIN/MAX 사용법 익히기
SELECT INVOICE_NO, LINE_NO, ITEM_NM, ORDER_QTY
      ,MIN(ORDER_QTY) OVER(PARTITION BY INVOICE_NO) AS MIN_1
      ,MIN(ORDER_QTY) OVER()                        AS MIN_2
      ,MAX(ORDER_QTY) OVER(PARTITION BY INVOICE_NO) AS MAX_1
      ,MAX(ORDER_QTY) OVER()                        AS MAX_2
  FROM LO_OUT_D
 WHERE INVOICE_NO IN ('346724703845', '346724706214', '346724706225')
;


-- 분석함수 2
-- 1)
SELECT OUTBOUND_DATE, OUTBOUND_BATCH, ORDER_QTY
      ,ROW_NUMBER()   OVER(PARTITION BY OUTBOUND_DATE ORDER BY OUTBOUND_DATE)  AS "일자단위 차수 순서"
      ,SUM(ORDER_QTY) OVER(PARTITION BY OUTBOUND_DATE ORDER BY OUTBOUND_BATCH) AS "일자단위 차수순 누계"
      ,SUM(ORDER_QTY) OVER(PARTITION BY OUTBOUND_DATE)                         AS "일자별 합계"
      ,SUM(ORDER_QTY) OVER(ORDER BY OUTBOUND_DATE)                             AS "일자순 누계"
--      ,SUM(ORDER_QTY) OVER(ORDER BY OUTBOUND_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS "일자순 누계"
      ,SUM(ORDER_QTY) OVER()                                                   AS "전체 합계" 
      ,COUNT(*)       OVER(PARTITION BY OUTBOUND_DATE)                         AS "일자단위 레코드수"
      ,COUNT(*)       OVER()                                                   AS "전체 레코드수"
  FROM (
        SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH, SUM(M2.ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
          WHERE OUTBOUND_DATE BETWEEN TO_DATE('2019-09-03', 'YYYY-MM-DD') AND TO_DATE('2019-09-10', 'YYYY-MM-DD')
            AND OUT_TYPE_DIV = 'M11'
          GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH
       )
 ORDER BY OUTBOUND_DATE, OUTBOUND_BATCH
;

--2)
SELECT OUTBOUND_DATE
      ,RANK() OVER(PARTITION BY OUTBOUND_DATE ORDER BY ORDER_QTY) AS "일자단위 수량 랭킹"
      ,OUTBOUND_BATCH
      ,ORDER_QTY
  FROM (
        SELECT OUTBOUND_DATE, OUTBOUND_BATCH, SUM(ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1 
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
           AND OUT_TYPE_DIV = 'M11'
         GROUP BY OUTBOUND_DATE, OUTBOUND_BATCH
       )
;

--3)
SELECT CASE WHEN OUTBOUND_DATE = LAG(OUTBOUND_DATE) OVER(ORDER BY "일자별 수량 합계" DESC, ORDER_QTY DESC) THEN ' ' 
            ELSE TO_CHAR(OUTBOUND_DATE, 'YY/MM/DD')
       END AS "출고일자"
      ,OUTBOUND_BATCH
      ,ORDER_QTY
      ,"일자별 수량 합계"
      ,"일자별 수량 합계 랭킹"
      ,"전체 랭킹"
  FROM (
        SELECT OUTBOUND_DATE
              ,OUTBOUND_BATCH
              ,ORDER_QTY
              ,DAILY_SUM_QTY AS "일자별 수량 합계"
              ,DENSE_RANK() OVER(ORDER BY DAILY_SUM_QTY DESC) AS "일자별 수량 합계 랭킹"
              ,RANK() OVER(ORDER BY ORDER_QTY DESC)           AS "전체 랭킹"
          FROM (
                SELECT M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH,
                            SUM(M2.ORDER_QTY) AS ORDER_QTY,
                            SUM(SUM(M2.ORDER_QTY)) OVER(PARTITION BY M1.OUTBOUND_DATE) AS DAILY_SUM_QTY
                  FROM LO_OUT_M M1
                       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
                 WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-10'
                   AND M1.OUT_TYPE_DIV = 'M11'
                 GROUP BY M1.OUTBOUND_DATE, M1.OUTBOUND_BATCH 
               )
       )
 ORDER BY "일자별 수량 합계" DESC, ORDER_QTY DESC, OUTBOUND_BATCH
;

--4)
SELECT CASE WHEN RNK <= 5 THEN TO_CHAR(OUTBOUND_DATE, 'YYYY-MM-DD')
            ELSE '기타'
       END AS OUTBOUND_DATE
      ,SUM(ORDER_QTY) AS SUM_QTY
      ,MIN(RNK) AS RNK
      ,SUM(RATE) AS RATE
  FROM (
        SELECT M1.OUTBOUND_DATE, SUM(M2.ORDER_QTY) AS ORDER_QTY
              ,ROW_NUMBER() OVER(ORDER BY SUM(M2.ORDER_QTY)) AS RNK
              ,ROUND(RATIO_TO_REPORT(SUM(M2.ORDER_QTY)) OVER() * 100, 3) AS RATE
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-01' AND '2019-09-15'
         GROUP BY M1.OUTBOUND_DATE
       )
 GROUP BY CASE WHEN RNK <= 5 THEN TO_CHAR(OUTBOUND_DATE) ELSE '기타' END
 ORDER BY RNK
;
 
-- 분석함수 3
--1)
SELECT OUTBOUND_DATE, "순위", ITEM_NM, ORDER_QTY
  FROM (
        SELECT OUTBOUND_DATE
             ,RANK() OVER(PARTITION BY OUTBOUND_DATE ORDER BY SUM(ORDER_QTY) DESC) AS "순위"
              ,ITEM_NM
              ,SUM(ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
         GROUP BY OUTBOUND_DATE, ITEM_NM
         ORDER BY OUTBOUND_DATE
       )
WHERE "순위" <= 3
;

--2)
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS OUT_DATE
      ,RNK, ITEM_NM, T2.SUM_QTY
  FROM (
        SELECT OUTBOUND_DATE
              ,ROW_NUMBER() OVER(PARTITION BY OUTBOUND_DATE ORDER BY T1.SUM_QTY DESC) AS RNK
              ,ITEM_NM
              ,T1.SUM_QTY
          FROM (
                SELECT M1.OUTBOUND_DATE
                     , M2.ITEM_NM
                     , SUM(M2.ORDER_QTY) AS SUM_QTY
                  FROM LO_OUT_M M1
                       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
                 WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
                 GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
               ) T1
       ) T2
 WHERE RNK <= 3
;

--3)
SELECT LAG(NULL, 1, OUTBOUND_DATE) OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS OUT_DATE
      ,RNK, ITEM_NM, T2.SUM_QTY
      ,T2."점유율"
      ,SUM("점유율") OVER(PARTITION BY OUTBOUND_DATE ORDER BY RNK) AS "누적점유율"
  FROM (
        SELECT OUTBOUND_DATE, ITEM_NM, SUM_QTY
              ,ROW_NUMBER() OVER(PARTITION BY OUTBOUND_DATE ORDER BY T1.SUM_QTY DESC) AS RNK
              ,ROUND(RATIO_TO_REPORT(T1.SUM_QTY) OVER(PARTITION BY OUTBOUND_DATE) * 100, 2) AS "점유율"
          FROM (
                SELECT M1.OUTBOUND_DATE
                     , M2.ITEM_NM
                     , SUM(M2.ORDER_QTY) AS SUM_QTY
                  FROM LO_OUT_M M1
                       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
                 WHERE M1.OUTBOUND_DATE BETWEEN '2019-09-03' AND '2019-09-05'
                 GROUP BY M1.OUTBOUND_DATE, M2.ITEM_NM
               ) T1
       ) T2
 WHERE RNK <= 3