--1) 
SELECT CASE WHEN RN <= 3 THEN DY ELSE 'etc' END AS DY
      ,SUM(ORDER_QTY) AS ORDER_QTY
  FROM (
        SELECT TO_CHAR(TO_DATE(OUTBOUND_DATE, 'YYYY-MM-DD'), 'DY') AS DY
              ,ROW_NUMBER() OVER(ORDER BY SUM(ORDER_QTY) DESC) AS RN
              --,TO_CHAR(TO_DATE(OUTBOUND_DATE, 'YYYY-MM-DD'), 'D') AS D
              ,SUM(ORDER_QTY) AS ORDER_QTY
          FROM LO_OUT_M M1
               JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
         WHERE OUTBOUND_DATE BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(:OUT_DATE, 'YYYYMMDD'), -1), 'YYYYMMDD') AND :OUT_DATE
         GROUP BY TO_CHAR(TO_DATE(OUTBOUND_DATE, 'YYYY-MM-DD'), 'DY')
       )
 GROUP BY CASE WHEN RN <= 3 THEN DY ELSE 'etc' END
 ORDER BY CASE WHEN DY = 'etc' THEN 2 ELSE 1 END
         ,ORDER_QTY DESC
;
 
--2)
SELECT SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'D') IN ('2','3','4','5','6') THEN M2.ORDER_QTY ELSE 0 END) AS "평일출고"
      ,SUM(CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'D') IN ('1', '7') THEN M2.ORDER_QTY ELSE 0 END) AS "주말출고"
  FROM LO_OUT_M M1
  JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(:OUT_DATE, 'YYYYMMDD'), -1), 'YYYYMMDD') 
                            AND :OUT_DATE
;                        

--3)
SELECT CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'D') IN ('2','3','4','5','6') THEN "평일" ELSE "주말" END AS WEEK
      ,SUM(ORDER_QTY) AS SUM_QTY
  FROM LO_OUT_M M1
  JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(:OUT_DATE, 'YYYYMMDD'), -1), 'YYYYMMDD') 
                            AND :OUT_DATE
                            
 GROUP BY CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'D') IN ('2','3','4','5','6') THEN "평일" ELSE "주말" END
 ORDER BY CASE WHEN TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'D') IN ('2','3','4','5','6') THEN "평일" ELSE "주말" END
;

--4)
SELECT DISTINCT M1.OUTBOUND_DATE
      ,TO_CHAR(TO_DATE(M1.OUTBOUND_DATE, 'YYYY-MM-DD'), 'DY') AS DY
  FROM LO_OUT_M M1
       JOIN LO_OUT_D M2 ON M2.INVOICE_NO = M1.INVOICE_NO
 WHERE M1.OUTBOUND_DATE BETWEEN TO_CHAR(ADD_MONTHS(TO_DATE(:OUT_DATE, 'YYYYMMDD'), -1), 'YYYYMMDD') AND :OUT_DATE
--   AND M2.ORDER_QTY IS NULL
 ORDER BY M1.OUTBOUND_DATE
;


















